name: Auto request review
description: Automatically request reviewer from teams and mentorship groups
inputs:
  token:
    required: true
    description: GitHub token
  count:
    required: false
    default: "2"
    description: How many reviewers to request. Default 2.
  config_gist_id:
    required: true
    description: Gist id to config.yml
runs:
  using: node20
  main: dist/index.js
